package com.fogistanbul.crm.entity.enums;

public enum NotificationType {
    TASK_ASSIGNED,
    TASK_COMPLETED,
    TASK_OVERDUE,
    TASK_STATUS_CHANGED,
    MESSAGE_RECEIVED,
    APPROVAL_REQUEST,
    APPROVAL_DECIDED,
    MEETING_REMINDER,
    SHOOT_CREATED,
    SHOOT_REMINDER,
    SHOOT_UPDATED,
    CONTENT_PLAN_CREATED,
    CONTENT_PLAN_UPDATED,
    SURVEY_REQUEST,
    FILE_SHARED,
    SYSTEM
}
